name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ffggaass-backend:latest .
          docker tag ffggaass-backend:latest ${{ secrets.DOCKER_USERNAME }}/ffggaass-backend:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ffggaass-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Docker container
        run: |
          docker run -d --name ffggaass-backend -p 9091:9091 \
          -e MONGODB_URL_ONLINE="${{ secrets.MONGODB_URL_ONLINE }}" \
          ${{ secrets.DOCKER_USERNAME }}/ffggaass-backend:latest
